---
title: "Análise de Resíduos e Diagnósticos"
---

::: {.chapterintro data-latex=""}
Nessa aula vamos iniciar a descrição de métodos e estatísticas para diagnóstico em modelos de regressão linear. São utilizadas para avaliar ou verificar se as pressuposições foram atendidas e se existem pontos atípicos no conjunto de dados. De maneira geral, esses métodos e estatísticas estão relacionadas aos resíduos do modelo de regressão ajustado aos dados.

Essa aula é baseada no **Capítulo 4 - Análise de Resíduos e Diagnósticos**  da apostila _Modelos de Regressão_ (Demétrio e Zocchi, 2011) no livro **Applied Linear Statistical Models** (Kutner et al., 2008).
:::

## Introdução  

Um modelo de regressão linear (MRL) pode ser representado, de maneira geral, como um modelo de regressão linear múltiplo, ou seja,
$$
y_i = \beta_{0} + \beta_{1}x_{1i} + \beta_{2}x_{2i} + \ldots + \beta_{k}x_{ki} + \varepsilon_i,
$$ {#eq-mrlm}
em que $y_i$ é a _i-ésimo_ valor observado, com $i=1,2,\ldots,n$; $x_{1i}, x_{2i}, \ldots, x_{ki}$ são os valores das _k-ésimas_ variáveis independentes ou explicativas associadas à observação $y_i$;
$\beta_0$, $\beta_1$, $\beta_2$, $\ldots$, $\beta_k$ são os $k+1$ parâmetros do modelo; e $\varepsilon_i$ é o _i-ésimo_ erro, sendo os erros idenpendentes e identicamente distribuídos segundo uma normal com variância única, ou seja, $\varepsilon_i \sim \textrm{N}(0; \sigma^{2})$.

O modelo definido na @eq-mrlm pode ser representado matricialmente como
$$
\mathbf{Y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\varepsilon},
$$ {#eq-mrlmat}
em que $\mathbf{Y}$ é o vetor $n \times 1$ de observações; $\mathbf{X}$ é uma matriz $n \times (k+1)$, denominada de matriz de incidência ou de modelo; $\boldsymbol{\beta}$ é o vetor $(k+1) \times 1$ de parâmetros; e $\boldsymbol{\varepsilon}$ é o vetor $n \times 1$ de erros, tal que $\boldsymbol{\varepsilon} \sim N(\boldsymbol{\phi},\boldsymbol{\Sigma})$, em que $\boldsymbol{\phi}$ é um vetor $n \times 1$ de 0's e $\boldsymbol{\Sigma}$ é uma matriz, $n \times n$, de variâncias e covariâncias dos erros ($\varepsilon_i$'s), que, sendo os erros idenpendentes e com variância única $\sigma^2$, $\boldsymbol{\Sigma} = \mathbf{I} \sigma^2$.

É importante observar que pressuposições em relação aos erros, como independência, homocedasticidade e normalidade, são assumidas e, portanto, todo o processo de inferência é válido somente sob a condição que essas pressuposições são atendidas. Porém, de acordo com Demétrio e Zocchi (2011), se as pressuposições forem violadas, podem ocorrer _falhas sistemáticas_, como não normalidade, heterocedasticidade e não independência dos erros, não linearidade, dentre outros e a análise resultante pode levar a conclusões duvidosas ou equivocadas. 

Em estudos de regressão linear múltipla, um ponto $i$ corresponde à posição em um espaço multidimensional, definida por suas coordenadas, ou seja, $(y_i, x_{1i}, x_{2i}, \ldots, x_{ki})$ e um fato bastante comum e que deve ser considerado, é a presença de pontos atípicos (_falhas isoladas_), que podem influenciar, ou não, o ajuste do modelo. Esses pontos atípicos podem ocorrer por vários motivos, dentre os quais podemos citar:

- erros grosseiros na variável resposta ou nas variáveis explicativas, devido a mesurações erradas, erros no registro da observação ou erros de transcrição (como por exemplo, erros de digitação dos dados);

- observação obtida em condições distintas das demais, ou seja, falta de padronização durante as mensurações;

- modelo mal especiﬁcado, ocasionado, por exemplo, por falta de uma ou mais variáveis, modelo inadequado, dentre outros;

- escala errada e, portanto, os dados deveriam ser melhor representados considerando uma transformação do tipo logarıtmica ou raiz quadrada;

- considerar uma distribuição equivocada da variável resposta, o que não está diretamente relacionado aos ajustes de modelos de regressão linear vistos nesse curso, mas tem relação com o ajuste considerando outros métodos, como por exemplo, os modelos lineares generalizados.

Uma das maneiras para avaliar se um ponto é considerado atípico, consiste em utilizar o que é denominado de deleção. Nessa estratégia compara-se e avalia-se o ajuste do modelo considerando todos os pontos, com o ajuste do mesmo modelo, retirando ou desconsiderando os pontos atípicos. Nessa caso serão utilizadas estatísticas específicas, cuja notação envolve, geralmente, o uso de um índice entre parênteses. Por exemplo, $\hat{\sigma}^2_{(i)}$ representa a variância residual estimada, tendo excluído o ponto $i$.

Portanto, após o ajuste de um MRL é importante avaliar ou verificar se as pressuposições foram atendidas e se existem pontos atípicos no conjunto de dados. Para isso, geralmente são considerados:

- os valores estimados: $\hat{y}_i$ ou, matricialmente $\hat{\mathbf{Y}}$;

- os erros estimados, também chamados de resíduos: $\hat{\varepsilon}_i = y_i - \hat{y}_i$ ou, matricialmente $\boldsymbol{\varepsilon} = \mathbf{Y} - \hat{\mathbf{Y}}$;

- variância residual estimada: $\hat{\sigma}^2 = QMErro$; e

- os elementos da diagonal da _**matriz hat**_ ou de projeção $\mathbf{H}$, denominados de _leverage_. Conforme definido em outras aulas, essa matriz é dada por
$$
\mathbf{H} = \mathbf{X} (\mathbf{X}' \mathbf{X})^{-1} \mathbf{X}' =
\begin{bmatrix}
h_1 & h_{12} & h_{13} & \cdots & h_{1n} \\
h_{12} & h_2 & h_{23} & \cdots & h_{2n} \\
h_{13} & h_{23} & h_3 & \cdots & h_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\ 
h_{1n} & h_{2n} & h_{3n} & \cdots & h_n \\
\end{bmatrix},
$$
na qual $h_i$, com $i=1,2,\ldots,n$, é o _leverage_ $i$ associado à _i-ésima_ observação $y_i$. Pode-se observar que
$$
\mathbf{H} = \mathbf{X} (\mathbf{X}' \mathbf{X})^{-1} \mathbf{X}' =
\begin{bmatrix}
1 & x_{11} & x_{21} & \cdots & x_{k1} \\
1 & x_{12} & x_{22} & \cdots & x_{k2} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{1n} & x_{2n} & \cdots & x_{kn} \\
\end{bmatrix} (\mathbf{X}' \mathbf{X})^{-1}
\begin{bmatrix}
1 & 1 & \cdots & 1 \\ 
x_{11} & x_{12} & \cdots & x_{1n} \\
x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{k1} & x_{k2} & \cdots & x_{kn} \\
\end{bmatrix}
$$
e, portanto,
$$
\begin{array}{rcl}
h_1 & = & 
\begin{bmatrix}
1 & x_{11} & x_{21} & \cdots & x_{k1} 
\end{bmatrix} (\mathbf{X}' \mathbf{X})^{-1}
\begin{bmatrix}
1 \\ x_{11} \\ x_{21} \\ \vdots \\ x_{k1} 
\end{bmatrix} \\
h_2 & = & 
\begin{bmatrix}
1 & x_{12} & x_{22} & \cdots & x_{k2} 
\end{bmatrix} (\mathbf{X}' \mathbf{X})^{-1}
\begin{bmatrix}
1 \\ x_{12} \\ x_{22} \\ \vdots \\ x_{k2} 
\end{bmatrix} \\
\vdots & \vdots & \qquad \qquad \qquad \vdots \\
h_n & = & 
\begin{bmatrix}
1 & x_{1n} & x_{2n} & \cdots & x_{kn} 
\end{bmatrix} (\mathbf{X}' \mathbf{X})^{-1}
\begin{bmatrix}
1 \\ x_{1n} \\ x_{2n} \\ \vdots \\ x_{kn} 
\end{bmatrix}
\end{array}.
$$
Dessa forma, pode-se definir, de maneira geral, $h_i = \mathbf{x}_i (\mathbf{X}'\mathbf{X})^{-1} \mathbf{x}'_i$, em que $\mathbf{x}_i = \begin{bmatrix} 1 & x_{1i} & x_{2i} & \cdots & x_{ki} \end{bmatrix}$.

Segundo Demétrio e Zocchi (2011), as técnicas utilizadas na verificação do ajuste de um modelo podem ser informais ou formais. A

- **Técnicas informais:** incluem a avaliação visual de gráficos específicos, buscando identificar padrões que indiquem um ajuste ruim do modelo proposto ou a presença de pontos discrepantes. 

- **Técnicas formais:** envolvem o ajuste de diferentes modelos, sendo o modelo proposto aninhado em uma classe maior, que contempla a inclusão de mais um parâmetro ou um vetor de parâmetros. As mais utilizadas têm como base a aplicação de testes _score_ ou da _razão de verossimilhanças_. Essa adição de novos parâmetros contemplam:
  
  - inclusão de uma covariável adicional;

  - aninhamento de uma variável $X$ em uma família indexada por um parâmetro $\gamma$, sendo um exemplo a família Box-Cox;

  - inclusão de uma variável construída;

  - inclusão de uma variável _dummy_, que assume valor 0 (zero) para os pontos discrepantes e 1 (um) para os demais. Isso equivale a realizar as análises desconsiderando ou não as observações referentes aos pontos discrepantes e avaliar se ocorre uma alteração significativa na $SQErro$. Porém, deve-se inicialmente identificar os pontos discrepantes.


## Tipos de resíduos

Conforme descrito anteriormente, os resíduos são importantes na avaliação do ajuste de MRL e na identificação de pontos atípicos. Até o momento definimos o resíduo como $\hat{\varepsilon}_i = y_i - \hat{y}_i$, que corresponde ao denominado _**resíduo ordinário**_. Porém, esse não é único tipo de resíduo utilizado. A seguir, definiremos três tipos de resíduos: resíduo ordinário, resíduo estudentizado internamente e resíduo estudentizado externamente.

### Resíduos ordinários

Conforme definido anteriormente, o resíduo ordinário é dado por:
$$
\hat{\varepsilon}_i = y_i - \hat{y}_i,
$$
em que $y_i$ e $\hat{y}_i$ são, respectivamente, o _i-ésimo_ valor observado e estimado por meio do modelo ajustado. O vetor contendo os resíduos ordinários é dado por
$$
\hat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \hat{\mathbf{Y}},
$$
em que $\mathbf{Y}$ e $\hat{\mathbf{Y}}$ são, respectivamente, os vetores $n \times 1$ de valores observados e estimados. Esse vetor também pode ser representado sa seguinte forma:
$$
\hat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \mathbf{X} \hat{\boldsymbol{\beta}} = \mathbf{Y} - \mathbf{X} (\mathbf{X}'\mathbf{X})^{-1}\mathbf{X}'\mathbf{Y} = \mathbf{Y} - \mathbf{HY} = \left( \mathbf{I} - \mathbf{H} \right) \mathbf{Y}.
$$

Vale ressaltar que os erros ($\varepsilon_i$) são idenpendentes e identicamente distribuídos com variância única. Porém, isso não é válido para os resíduos ou erros estimados ($\hat{\varepsilon}_i$). No caso dos resíduos ordinários tem-se: 

- Variância do resíduo ordinário:
$$
V(\hat{\boldsymbol{\varepsilon}}) = V \left[ \left( \mathbf{I} - \mathbf{H} \right) \mathbf{Y} \right] = \left( \mathbf{I} - \mathbf{H} \right)Var \left(  \mathbf{Y} \right) = \left( \mathbf{I} - \mathbf{H} \right) \sigma^2
$$
ou para o _i-ésimo_ resíduo ordinário:
$$
V(\hat{\varepsilon}_i) = (1-h_i)\sigma^2;
$$
- Covariância dos _i-ésimo_ e _i'-ésimo_ resíduos ordinários:
$$
COV(\hat{\varepsilon}_i,\hat{\varepsilon}_{i'}) = -h_{ii'}\sigma^2.
$$
Como os resíduos ordinários têm variâncias diferentes ou heterogêneas, utilizá-los na avaliação do ajuste de um MRL pode não ser adequado. Por isso, foram propostas diferentes padronizações desses resíduos para contornar os problemas. Dentre essas padronizações podemos citar: os resíduos estudentizados internamente e os resíduos estudentizados externamente.

### Resíduos estudentizados internamente (_Studentized residual_)

Um estimador não viesado para $V(\hat{\varepsilon}_i)$ é dado por:
$$
\hat{V}(\hat{\varepsilon}_i) = (1-h_i)\hat{\sigma}^2 = (1-h_i) QMErro.
$$
Como $E(\hat{\varepsilon}_i) = 0$, o resíduo estudentizado internamente é definido por:
$$
rsi_i = \dfrac{\hat{\varepsilon}_i}{\sqrt{\hat{V}(\hat{\varepsilon}_i)}} = \dfrac{\hat{\varepsilon}_i}{\sqrt{(1-h_i) QMErro}}.
$$
Segundo Demétrio e Zocchi (2011), os $rsi$ são mais sensíveis do que os resíduos ordinários, pois variâncias distintas são consideradas. Além disso, um valor discrepante pode alterar consideravelmente a variância residual ($QMErro$). Ademais, o numerador e o denominador são variáveis dependentes, ou seja, $COV(\hat{\varepsilon}_i, QMErro) \ne 0$.


### Resíduos estudentizados externamente (_jacknifed residuals_, _deletion residuals_, externally studentized residual_ ou _RStudent_)

Para contornar o problema da não independência entre $\hat{\varepsilon}_i$ e $QMErro$ na padronização dos resíduos, foi definido o resíduo estudentizado externamente, dado por:
$$
rse_{(i)} = \dfrac{\hat{\varepsilon}_i}{\sqrt{(1-h_i) QMErro_{(i)}}} = \dfrac{\hat{\varepsilon}_i}{\sqrt{(1-h_i) \hat{\sigma}^2_{(i)}}} = \dfrac{\hat{\varepsilon}_i}{\hat{\sigma}_{(i)}\sqrt{(1-h_i)}},
$$
em que $QMErro_{(i)} = \hat{\sigma}^2_{(i)}$ é quadrado médio do erro livre da observação $i$, ou seja, obtido no ajuste do modelo sem considerar a observação $i$.

Pode-se demonstrar que:
$$
rse_{(i)} = rsi_{i} \sqrt{\dfrac{n-p-1}{n-p-rsi_i^2}},
$$
em que $p = k+1$ corresponde ao número de parâmetros do modelo.

Segundo Demétrio e Zocchi (2011), uma das vantagens de se utilizar o $rse_{(i)}$ é que, sob a condição de normalidade dos erros, esse resíduo tem distribuição $t$ de Student com $(n-p-1)$ graus de liberdade. Porém, não se recomenda a utilização de testes de significância na análise de resíduos. No entanto, uma observação que apresente $|rse_{(i)}|$ maior que o percentil $100 \left( 1-\dfrac{\alpha}{2n} \right)$ da distribuição $t$ com $(n-p-1)$ graus de liberdade, em que $\alpha$ é o nível de significância, deve ser avaliada com atenção especial.


## Estatísticas para diagnósticos

Neste tópico apresentaremos e descreveremos de maneira sucinta as seguintes estatísticas: $h_i$ (_leverage_), $DFBeta$, $DFFitS$, Distância de Cook ($D_{(i)}$ ou $C_i$) e _COVRATIO_.

Essas estatísticas são utilizadas com o objetivo de identificar pontos aberrantes, atípicos ou extremos (_outliers_). Estes são pontos com $h_i$ e/ou resíduos grandes. Para isso, conforme Demétrio e Zocchi (2011), é importante considerar os conceitos de _leverage_, inconsistência e influência, que estão ilustrados graficamente na Figura 4.1 de Demétrio e Zocchi (2011, p.104). A seguir é apresentada uma breve descrição desses conceitos.

  **a. Inconsistência:** um valor inconsistente apresenta $|rse_{(i)}| \ge t_{(\alpha/2n; n-p-1)}$, com nível de significância igual a $100\alpha\%$ e ele é considerado um _outlier_ quando o _leverage_ $(h_i)$ for pequeno e o $rse_{(i)}$ for grande. Na Figura 4.1 de Demétrio e Zocchi (2011), compare os gráficos (a) e (c) com o (b).
  
  **b. Ponto de alavanca:** um ponto é considerado como de alavanca quando apresenta $h_i$ grande, em geral quando $h_i \ge \frac{2p}{n}$. Pode ser considerado como bom ou ruim, o que pode ser visualizado na Figura 4.1 de Demétrio e Zocchi (2011) e comparando os gráficos (b) e (c) com o (a).
  
  **c. Ponto influente:** esse é caracterizado por uma observação que está distante das demais e que, se for desconsiderado nas análises, leva a mudanças consideráveis no ajuste do modelo. Ela pode ou não ser influente, o que pode ser visualizado ao comparar os gráficos (a) e (b) com o (c), na Figura 4.1 de Demétrio e Zocchi (2011). Uma observação influente pode ou não ser um _outlier_ e ela pode ser influente de diferentes formas: 
  
  (i) no ajuste do modelo ($DFFitS_{(i)}$ e $D_{(i)}$ ou $C_i$ grandes);  
  (ii) no conjunto das estimativas dos parâmetros do modelo ($DFBeta_{(i)}$ grande); 

  (iii) na estimativa de um $\beta_j$ específico ($DFBeta_{(i)}$ grande para um específico $\beta_j$); 
  
  (iv) na escolha de uma transformação da variável resposta ou de uma variável explicativa.
  
No R (Core Team, 2025), ao utilizar a função `influence.measures()`, a _i-ésima_ observação é considerada influente se:

  - $|DFBetaS_{(i)}| > 1$; ou
  
  - $DFFitS_{(i)} > 3 \sqrt{\dfrac{p}{n-p}}$; ou
  
  - $|1-COVRATIO| > \dfrac{3p}{n-p}$; ou
  
  - $D_{(i)} > F_{(0,50;p;n-p)}$; ou
  
  - $h_i > \dfrac{3p}{n}$.
  


### Elementos da diagonal da matriz $\mathbf{H}$ ($h_i$)

Os elementos da diagonal principal da matriz $\mathbf{H}$, os $h_i's$ são conhecidos como _leverages_. Conforme definido anteriormente,
$$
\mathbf{H} = \mathbf{X} (\mathbf{X}' \mathbf{X})^{-1} \mathbf{X}' =
\begin{bmatrix}
h_1 & h_{12} & h_{13} & \cdots & h_{1n} \\
h_{12} & h_2 & h_{23} & \cdots & h_{2n} \\
h_{13} & h_{23} & h_3 & \cdots & h_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\ 
h_{1n} & h_{2n} & h_{3n} & \cdots & h_n \\
\end{bmatrix},
$$
ou ainda, 
$$
h_i = \mathbf{x}_i (\mathbf{X}'\mathbf{X})^{-1} \mathbf{x}'_i
$$

### $DFBeta_{(i)}$ ou $DFBetaS_{(i)}$ 

Essa estatística é utilizada para avaliar a alteração que ocorre m $\hat{\boldsymbol{\beta}}$ ao se retirar ou desconsiderar a _i-ésima_ observação. É definido por:
$$
DFBeta_{(i)} = \hat{\boldsymbol{\beta}} - \hat{\boldsymbol{\beta}}_{(i)} = \dfrac{1}{1-h_i} (X'X)^{-1} \mathbf{x}_i \hat{\boldsymbol{\varepsilon}}_i.
$$

Kutner et al. (2008) apresenta a estatística $DFBetaS_{(i)}$ que, basicamente, consiste na divisão do $DFBeta_{(i)}$ pela estimativa do desvio padrão do $\hat{\beta}_j$, em que $\beta_j$ corresponde a um coeficiente de regressão específico, com $j=1,2, \ldots, k$. É dada por:
$$
DFBetaS_{(i)} = \dfrac{\beta_j - \hat{\beta}_{j(i)}}{\sqrt{\hat{\sigma}^2_{(i)} c_{kk}}},
$$
em que $c_{kk}$ é o _k-ésimo_ elemento da diagonal de $(\mathbf{X}'\mathbf{X})^{-1}$.


### $DFFitS_{(i)}$ 

Utilizada para avaliar o efeito da retirada da _i-ésima_ observação no valor predito ($\hat{y}_i$). É definida por:
$$
DFFitS_{(i)} = \dfrac{DFFit_{(i)}}{\sqrt{h_i \hat{\sigma}_{(i)}}} = \dfrac{\mathbf{x}_i \left( \hat{\boldsymbol{\beta}} - \hat{\boldsymbol{\beta}_{(i)}} \right)}{\sqrt{h_i \hat{\sigma}_{(i)}}} = \dfrac{\hat{y}_i - \hat{y}_{i(i)}}{\sqrt{h_i \hat{\sigma}_{(i)}}}
$$
ou
$$
DFFitS_{(i)} = \left( \dfrac{h_i}{1-h_i} \right)^{\frac{1}{2}} \dfrac{\hat{\varepsilon}_i}{\hat{\sigma}_{(i)} \sqrt{1-h_i}} = \left( \dfrac{h_i}{1-h_i} \right)^{\frac{1}{2}} rse_{(i)}
$$
em que $\dfrac{h_i}{1-h_i}$ é chamado de potencial de influência, ou seja, mede a distância de um ponto em relação às demais observações.

De acordo com Belsley, Kuh e Welsch (1980 apud Demétrio e Zocchi, 2011, p. 107), valores absolutos de $DFFitS_{(i)}$ que excederem $2 \sqrt{\dfrac{p}{n}}$ indicam observações influentes.


### Distância de Cook

A Distância de Cook - $D_{(i)}$, assim como a $DFFitS_{(i)}$, é utilizada na avaliação do afastamento dos $\hat{y}_i's$ provocado pela retirada da _i-ésima_ observação. É dada por:
$$
D_{(i)} = \dfrac{\displaystyle \sum_{i=1}^{n} \left( \hat{y}_i - \hat{y}_{i(i)} \right)^2}{p \hat{\sigma}^2} = \dfrac{\left( \hat{\boldsymbol{\beta}}_i - \hat{\boldsymbol{\beta}}_{i(i)}  \right)' \mathbf{X}'\mathbf{X} \left( \hat{\boldsymbol{\beta}}_i - \hat{\boldsymbol{\beta}}_{i(i)}  \right)}{p \hat{\sigma}^2} = \dfrac{h_i}{(1-h_i)^2} \cdot \dfrac{\hat{\varepsilon}_i^2}{p \hat{\sigma}^2}
$$
ou
$$
D_{(i)} = \dfrac{h_i}{(1-h_i)} \cdot \dfrac{1}{p} \cdot rsi_i^2.
$$

**- Distância de Cook modificada:** \
Atkinson (1981 apud Demétrio e Zocchi, 2011, p. 107) sugere uma modificação em $D_{(i)}$ e, assim, a Distância de Cook modificada é dada por:
$$
C_i = \left( \dfrac{n-p}{p} \cdot \dfrac{h_i}{1-h_i} \right)^\frac{1}{2} |rse_{(i)}| = \left( \dfrac{n-p}{p} \right)^\frac{1}{2} DFFitS_{(i)}.
$$

### $COVRATIO$

Essa estatística é utilizada para avaliar a influência de uma observação sobre o volume do elipsoide de confiança. Pode ser definida como uma medida de alteração na precisão das estimativas dos parâmetros, obtidas por meio de modelos ajustados na presença e na ausência da _i-ésima_ observação.

De acordo com Demétrio e Zocchi (2011), sabe-se que a região de $100(1-\alpha)\%$ de confiança para o vetor de parâmetros $\boldsymbol{\beta}$ é dada pelos valores de $\boldsymbol{\beta}$ tais que
$$
\left( \boldsymbol{\beta} - \hat{\boldsymbol{\beta}}  \right)' \mathbf{X}'\mathbf{X} \left( \boldsymbol{\beta} - \hat{\boldsymbol{\beta}}  \right) \le p\hat{\sigma}^2 F_{(\alpha,\nu,\gamma)},
$$
em que $F_{(\alpha,\nu,\gamma)}$ é o quantil na distribuição $F$ referente ao percentil $100\alpha\%$, com os graus de liberdade $\nu = p$ e $\gamma = GLErro$. Essa região é delimitada por um elipsoide cujo volume, dependente do determinate de $\mathbf{X}'\mathbf{X}$ e de $\hat{\sigma}^2$, é dado por
$$
E \varpropto \left\{ \dfrac{\hat{\sigma}^{2p}}{|\mathbf{X}'\mathbf{X}|} \right\}^\frac{1}{2}.
$$
Quando a _i-ésima_ observação é desconsiderada nos ajustes, o volume passa a ser
$$
E_{(i)} \varpropto \left\{ \dfrac{\hat{\sigma}_{(i)}^{2p}}{|\mathbf{X}_{(i)}'\mathbf{X}_{(i)}|} \right\}^\frac{1}{2}.
$$
Como uma forma de se determinar a influência da _i-ésima_ observação sobre o volume do elipsoide de confiança, Belsley, Kuh e Welsch (1980 apud Demétrio e Zocchi, 2011, p. 136) propuseram a medida chamada $COVRATIO$, dada por:
$$
COVRATIO = \left\{ \dfrac{E_{(i)}}{E} \right\}^2.
$$

## Exemplo

Considere como exemplo de aplicação da Análise de Resíduos e Diagnósticos, o exemplo com os dados de altura e DAP das Sequoias. O seguinte script do R será utilizado:

```{r,warning=FALSE,message = FALSE, echo=TRUE, eval=FALSE}
###############################
## GES119 - Modelos Lineares I (2025-2)
## ANALISE DE RESIDUO E DIAGNOSTICOS
###############################
#
##########
## Esequoia$dap_cmemplo - Dados Sequoias
##########
#
rm(list=ls())
librarsequoia$altura_m(ggplot2)
librarsequoia$altura_m(readsequoia$dap_cml)
#
sequoia <- read_esequoia$dap_cmcel("Dados/sequoia.sequoia$dap_cmlssequoia$dap_cm")
str(sequoia)
##
#
### Diagrama de dispersao dos dados
plot(sequoia$altura_m~sequoia$dap_cm, xlab = "DAP (cm)", ylab = "Altura (m)")
#
### Ajuste do modelo de 1o. grau
mod1 <- lm(sequoia$altura_m~sequoia$dap_cm)
(summ1<- summary(mod1))
(an1<- anova(mod1))
plot(sequoia$altura_m~sequoia$dap_cm, xlab = "DAP (cm)", 
     ylab = "Altura (m)", pch=19)
# Grafico com a reta ajustada
dap_cm.graf<- seq(min(sequoia$dap_cm), max(sequoia$dap_cm), l=100)
altura_m.est<- summ1$coef[1,1] + summ1$coef[2,1]*dap_cm.graf
lines(dap_cm.graf, altura_m.est, col=2)
##
## RESIDUOS
#
## Residuos ordinarios
(rord<- residuals(mod1))
#
## Residuos estudentizados internamente (rsi)
(QMRes<- an1[2,3])
(n<- length(sequoia$altura_m))
p<- 2 # numero de parametros do modelo
(X<- model.matrix(sequoia$altura_m~sequoia$dap_cm))
(XlX<- t(X) %*% X)
(iXlX<- solve(XlX))
(H<- X %*% iXlX %*% t(X))
(h.i<- diag(H))
(rsi<- rord/sqrt((1-h.i)*QMRes))
rstandard(mod1)
cbind(rsi, rstandard(mod1))
# 
## Residuos estudentizados externamente (rse)
rse<-NULL
for(j in 1:n){
  mod1.i<- lm(sequoia$altura_m[-j]~sequoia$dap_cm[-j])
  QMRes.i<- anova(mod1.i)[2,3]
  rse<- c(rse, rord[j]/sqrt((1-h.i[j])*QMRes.i))
}
rse # ou
rsi*sqrt((n-p-1)/(n-p-rsi^2)) # ou ainda mais facil
rstudent(mod1)
cbind(rse, rsi*sqrt((n-p-1)/(n-p-rsi^2)), rstudent(mod1))
##
## Estatisticas para diagnosticos
#
beta.est<- summ1$coef[,1]
beta.est
DFBetaS<-NULL
for(j in 1:n){
  mod1.i<- lm(sequoia$altura_m[-j]~sequoia$dap_cm[-j])
  summ1.i<- summary(mod1.i)
  betaest.i<- summ1.i$coef[,1]
  QMRes.i<- anova(mod1.i)[2,3]
#  DFBeta<- rbind(DFBeta, t((1/(1-h.i[j])) * isequoia$dap_cmlsequoia$dap_cm %*% mat.sequoia$dap_cm[j,] %*% rord[j]))
#  DFBetaS<- rbind(DFBetaS, 
#                 ((beta.est-betaest.i)/sqrt(QMRes.i*diag(sequoia$dap_cmlsequoia$dap_cm))))
  DFBetaS.0<- (beta.est[1]-betaest.i[1])/
    sqrt(QMRes.i*iXlX[1,1])
  DFBetaS.1<- (beta.est[2]-betaest.i[2])/
    sqrt(QMRes.i*iXlX[2,2])
  DFBetaS<- rbind(DFBetaS, c(DFBetaS.0,DFBetaS.1))
  }
DFBetaS
DFFitS<- sqrt(h.i/(1-h.i))*rse
DFFitS
Cook<- (h.i/(1-h.i))*rsi^2/p
Cook
h.i
#
qf(0.5,2,7)
(IM<- influence.measures(mod1))
cbind(DFBetaS, IM$infmat[,1:2])
cbind(DFFitS, IM$infmat[,3])
cbind(Cook, IM$infmat[,5])
cbind(h.i, IM$infmat[,6])
summary(IM)
```








